apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hce.fullname" . }}-auth-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "hce.name" . }}-auth-server
    {{- include "hce.labels" . | nindent 4 }}
    {{- if .Values.portal.authServer.customLabels }}
      {{ toYaml .Values.portal.authServer.customLabels | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.portal.authServer.replicas }}
  {{- if .Values.portal.authServer.updateStrategy }}
  strategy:
  {{- toYaml .Values.portal.authServer.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "hce.name" . }}-auth-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "hce.name" . }}-auth-server
        {{- include "hce.labels" . | nindent 8 }}
        {{- if .Values.portal.authServer.customLabels }}
          {{ toYaml .Values.portal.authServer.customLabels | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: wait-for-mongodb
          image: {{ .Values.image.imageRegistryName }}/{{ .Values.portal.waitForMongodb.image.repository }}:{{ .Values.portal.waitForMongodb.image.tag }}
          imagePullPolicy: {{ .Values.portal.waitForMongodb.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            [
              "while [[ $(curl -sw '%{http_code}' http://{{ include "hce.fullname" . }}-mongo:{{ .Values.adminConfig.DB_PORT }} -o /dev/null) -ne 200 ]]; do sleep 5; echo 'Waiting for the MongoDB to be ready...'; done; echo 'Connection with MongoDB established'",
            ]
          resources:
            {{- toYaml .Values.portal.waitForMongodb.resources | nindent 12 }}
      containers:
        - name: auth-server
          image: {{ .Values.image.imageRegistryName }}/{{ .Values.portal.authServer.image.repository }}:{{ .Values.portal.authServer.image.tag }}
          imagePullPolicy: {{ .Values.portal.authServer.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.portal.authServer.serverContainerPort }}
              name: auth-server
            - containerPort: {{ .Values.portal.authServer.rpcContainerPort }}
              name: auth-rpc-server
          resources:
            {{- toYaml .Values.portal.authServer.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "hce.fullname" . }}-admin-secret
            - configMapRef:
                name: {{ include "hce.fullname" . }}-admin-config
          env:
            {{- range $key, $val := .Values.portal.authServer.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            - name: LITMUS_GQL_GRPC_ENDPOINT
              value: "{{ include "hce.fullname" . }}-server-service"
            - name: LITMUS_GQL_GRPC_PORT
              value: ":{{ .Values.portal.graphqlServer.service.graphqlRPCServer.targetPort }}"
    {{- with .Values.portal.authServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.portal.authServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.portal.authServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
