apiVersion: v1
kind: Service
metadata:
  name: {{ include "hce.fullname" . }}-auth-server-service
  namespace:  {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "hce.name" . }}-auth-service
    {{- include "hce.labels" . | nindent 4 }}
spec:
  type: {{ .Values.portal.authServer.service.type }}
  ports:
    - name: auth-server
      port: {{ .Values.portal.authServer.service.authServer.port }}
      targetPort: {{ .Values.portal.authServer.service.authServer.targetPort }}
    - name: auth-rpc-server
      port: {{ .Values.portal.authServer.service.authRPCServer.port }}
      targetPort: {{ .Values.portal.authServer.service.authRPCServer.targetPort }}
  selector:
    app.kubernetes.io/component: {{ include "hce.name" . }}-auth-server
