apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hce.fullname" . }}-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hce.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "hce.name" . }}-admin-secret
stringData:
  JWT_SECRET: "litmus-portal@123"
  DB_USER: "admin"
  DB_PASSWORD: "1234"