apiVersion: v1
kind: Service
metadata:
  name: license-service
  labels:
    app.kubernetes.io/component: {{ include "hce.name" . }}-license-service
    {{- include "hce.labels" . | nindent 4 }}
  namespace:  {{ .Release.Namespace }}
spec:
  type: {{ .Values.portal.licenseServer.service.type }}
  ports:
    - name: license-server
      port: {{ .Values.portal.licenseServer.service.licenseServer.port }}
      targetPort: {{ .Values.portal.licenseServer.service.licenseServer.targetPort }}
  selector:
    app.kubernetes.io/component: {{ include "hce.name" . }}-license-server
