apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hce.fullname" . }}-license-server
  namespace:  {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "hce.name" . }}-license-server
    {{- include "hce.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "hce.name" . }}-license-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "hce.name" . }}-license-server
        {{- include "hce.labels" . | nindent 8 }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-mongodb
          image: {{ .Values.image.imageRegistryName }}/{{ .Values.portal.waitForMongodb.image.repository }}:{{ .Values.portal.waitForMongodb.image.tag }}
          imagePullPolicy: {{ .Values.portal.waitForMongodb.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            [
              "while [[ $(curl -sw '%{http_code}' http://{{ include "hce.fullname" . }}-mongo:{{ .Values.adminConfig.DB_PORT }} -o /dev/null) -ne 200 ]]; do sleep 5; echo 'Waiting for the MongoDB to be ready...'; done; echo 'Connection with MongoDB established'",
            ]
          resources:
            {{- toYaml .Values.portal.waitForMongodb.resources | nindent 12 }}
      containers:
        - name: license-server
          image: {{ .Values.image.imageRegistryName }}/{{ .Values.portal.licenseServer.image.repository }}:{{ .Values.portal.licenseServer.image.tag }}
          envFrom:
            - secretRef:
                name: {{ include "hce.fullname" . }}-admin-secret
            - configMapRef:
                name: {{ include "hce.fullname" . }}-admin-config
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: {{ .Values.portal.licenseServer.containerPort }}
          imagePullPolicy: Always
          resources:
            {{- toYaml .Values.portal.licenseServer.resources | nindent 12 }}
      serviceAccountName: {{ .Values.portal.licenseServer.serviceAccountName }}
