apiVersion: v1
kind: Service
metadata:
  name: {{ include "hce.fullname" . }}-headless-mongo
  namespace:  {{ .Release.Namespace }}
  labels:
    app: mongo
    app.kubernetes.io/component: {{ include "hce.name" . }}-database
    {{- include "hce.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongo.service.type }}
  clusterIP: None
  ports:
    - name: mongodb
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.targetPort }}
  selector:
    app.kubernetes.io/component: {{ include "hce.name" . }}-database
