apiVersion: v1
kind: Service
metadata:
  name: {{ include "hce.fullname" . }}-server-service
  namespace:  {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "hce.name" . }}-server
    {{- include "hce.labels" . | nindent 4 }}
spec:
  type: {{ .Values.portal.graphqlServer.service.type }}
  ports:
    - name: graphql-server
      port: {{ .Values.portal.graphqlServer.service.graphqlServer.port }}
      targetPort: {{ .Values.portal.graphqlServer.service.graphqlServer.targetPort }}
    - name: gql-rpc-server
      port: {{ .Values.portal.graphqlServer.service.graphqlRPCServer.port }}
      targetPort: {{ .Values.portal.graphqlServer.service.graphqlRPCServer.targetPort }}
  selector:
    app.kubernetes.io/component: {{ include "hce.name" . }}-server
