apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hce.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "hce.name" . }}-server
    {{- include "hce.labels" . | nindent 4 }}
    {{- if .Values.portal.graphqlServer.customLabels }}
      {{ toYaml .Values.portal.graphqlServer.customLabels | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.portal.graphqlServer.replicas }}
  {{- if .Values.portal.graphqlServer.updateStrategy }}
  strategy:
  {{- toYaml .Values.portal.graphqlServer.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "hce.name" . }}-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "hce.name" . }}-server
        {{- include "hce.labels" . | nindent 8 }}
        {{- if .Values.portal.graphqlServer.customLabels }}
          {{ toYaml .Values.portal.graphqlServer.customLabels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.portal.graphqlServer.serviceAccountName }}
    {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: wait-for-mongodb
          image: {{ .Values.image.imageRegistryName }}/{{ .Values.portal.waitForMongodb.image.repository }}:{{ .Values.portal.waitForMongodb.image.tag }}
          imagePullPolicy: {{ .Values.portal.waitForMongodb.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            [
              "while [[ $(curl -sw '%{http_code}' http://{{ include "hce.fullname" . }}-mongo:{{ .Values.adminConfig.DB_PORT }} -o /dev/null) -ne 200 ]]; do sleep 5; echo 'Waiting for the MongoDB to be ready...'; done; echo 'Connection with MongoDB established'",
            ]
          resources:
            {{- toYaml .Values.portal.waitForMongodb.resources | nindent 12 }}
      containers:
        - name: graphql-server
          image: {{ .Values.image.imageRegistryName }}/{{ .Values.portal.graphqlServer.image.repository }}:{{ .Values.portal.graphqlServer.image.tag }}
          imagePullPolicy: {{ .Values.portal.graphqlServer.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.portal.graphqlServer.serverContainerPort }}
              name: gql-server
            - containerPort: {{ .Values.portal.graphqlServer.rpcContainerPort }}
              name: gql-rpc-server
          resources:
            {{- toYaml .Values.portal.graphqlServer.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: gql-server
            {{- toYaml .Values.portal.graphqlServer.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: gql-server
            {{- toYaml .Values.portal.graphqlServer.readinessProbe | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "hce.fullname" . }}-admin-secret
            - configMapRef:
                name: {{ include "hce.fullname" . }}-admin-config
          env:
            - name: LITMUS_PORTAL_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PORTAL_SCOPE
              value: {{ .Values.portalScope }}
            - name: SERVER_SERVICE_NAME
              value: {{ include "hce.fullname" . }}-server-service
            {{- if eq .Values.portalScope "namespace" }}
            - name: PORTAL_ENDPOINT
              value: "http://{{ include "hce.fullname" . }}-server-service:{{ .Values.portal.graphqlServer.service.graphqlServer.port }}"
            {{- end }}
            - name: LITMUS_AUTH_GRPC_ENDPOINT
              value: "{{ include "hce.fullname" . }}-auth-server-service"
            - name: LITMUS_AUTH_GRPC_PORT
              value: ":{{ .Values.portal.authServer.service.authRPCServer.targetPort }}"
            - name: INGRESS
              value: "{{ .Values.ingress.enabled }}"
            - name: INGRESS_NAME
              value: "{{ .Values.ingress.name }}"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- range $key, $val := .Values.portal.graphqlServer.imageEnv }}
            - name: {{ $key }}
              value: {{ $val }}
            {{- end }}
            {{- range $key, $val := .Values.portal.graphqlServer.genericEnv }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
    {{- with .Values.portal.graphqlServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.portal.graphqlServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.portal.graphqlServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}