apiVersion: batch/v1
kind: Job
metadata:
  name: upgrade-agent
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: upgrade-agent
          image: chaosnative/upgrade-agent-cp:master-ci
          envFrom:
            - configMapRef:
                name: litmus-portal-admin-config
            - secretRef:
                name: litmus-portal-admin-secret
          imagePullPolicy: Always
      restartPolicy: Never